TravelAgent/Areas/Admin/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using TravelAgent.Areas.Admin.Models;
using TravelAgent.Models;


namespace TravelAgent.Areas.Admin.Controllers
{
    [Authorize(Roles="Admin")]
   
    public class IndexController : Controller
    {
        // GET: Admin/Home
       ApplicationDbContext context = new ApplicationDbContext();

       public ActionResult Index()
        {
            var allusers = context.Users.ToList();
            var users = allusers.Where(x => context.Roles.Select(role => role.Name).Contains("User")).ToList();
            var userVM = users.Select(user => new UserViewModel { Username = user.UserName, Roles = string.Join(",", user.Roles.Select(role => role.RoleId)) }).ToList();

            var admins = allusers.Where(x => context.Roles.Select(role => role.Name).Contains("Admin")).ToList();
            var adminsVM = admins.Select(user => new UserViewModel { Username = user.UserName, Roles = string.Join(",", context.Roles.Select(role => role.Name)) }).ToList(); 
            var model = new GroupedUserViewModel{Users = userVM, Admins = adminsVM};

            return View(model);
        }
    }
}

TravelAgent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Travel Agent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Kura", "kur", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Admin", "Index", "Admin/Index")</li>
                            
                        }
                    }
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year All rights reserved </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>